from lotto import *
gc_lotto = GameConf()
gc_powerball = GameConf(game_name="PowerBall",min_number=1,max_number=45,keep_order=False,choose_special_on_play=True,special_name="PowerBall",special_min_number=1,special_max_number=20,number_qty_required = 5)
p = Persistance()

# field length: 10 [['Board', 'A', '11', '25', '27', '42', '43', 'Powerball:', '2', '']]
powerball_board_A = Board(board_name="A", balls=[], gameConf=gc_powerball)
b1 = Ball(11, gc_powerball)
b2 = Ball(25, gc_powerball)
b3 = Ball(27, gc_powerball)
b4 = Ball(42, gc_powerball)
b5 = Ball(43, gc_powerball)
b6 = Ball(2, gc_powerball, isSpecial=True)
powerball_board_A.add_ball(b1)
powerball_board_A.add_ball(b2)
powerball_board_A.add_ball(b3)
powerball_board_A.add_ball(b4)
powerball_board_A.add_ball(b5)
powerball_board_A.add_ball(b6)
# field length: 10 [['Board', 'B', '19', '20', '21', '22', '29', 'Powerball:', '15', '']]
powerball_board_B = Board(board_name="B", balls=[], gameConf=gc_powerball)
b1 = Ball(19, gc_powerball)
b2 = Ball(20, gc_powerball)
b3 = Ball(21, gc_powerball)
b4 = Ball(22, gc_powerball)
b5 = Ball(29, gc_powerball)
b6 = Ball(15, gc_powerball, isSpecial=True)
powerball_board_B.add_ball(b1)
powerball_board_B.add_ball(b2)
powerball_board_B.add_ball(b3)
powerball_board_B.add_ball(b4)
powerball_board_B.add_ball(b5)
powerball_board_B.add_ball(b6)
# field length: 10 [['Board', 'C', '1', '6', '8', '31', '33', 'Powerball:', '11', '']]
powerball_board_C = Board(board_name="C", balls=[], gameConf=gc_powerball)
b1 = Ball(1, gc_powerball)
b2 = Ball(6, gc_powerball)
b3 = Ball(8, gc_powerball)
b4 = Ball(31, gc_powerball)
b5 = Ball(33, gc_powerball)
b6 = Ball(11, gc_powerball, isSpecial=True)
powerball_board_C.add_ball(b1)
powerball_board_C.add_ball(b2)
powerball_board_C.add_ball(b3)
powerball_board_C.add_ball(b4)
powerball_board_C.add_ball(b5)
powerball_board_C.add_ball(b6)
# field length: 10 [['Board', 'D', '4', '12', '16', '17', '23', 'Powerball:', '18', '']]
powerball_board_D = Board(board_name="D", balls=[], gameConf=gc_powerball)
b1 = Ball(4, gc_powerball)
b2 = Ball(12, gc_powerball)
b3 = Ball(16, gc_powerball)
b4 = Ball(17, gc_powerball)
b5 = Ball(23, gc_powerball)
b6 = Ball(18, gc_powerball, isSpecial=True)
powerball_board_D.add_ball(b1)
powerball_board_D.add_ball(b2)
powerball_board_D.add_ball(b3)
powerball_board_D.add_ball(b4)
powerball_board_D.add_ball(b5)
powerball_board_D.add_ball(b6)
# field length: 10 [['Board', 'E', '15', '20', '23', '25', '27', 'Powerball:', '17', '']]
powerball_board_E = Board(board_name="E", balls=[], gameConf=gc_powerball)
b1 = Ball(15, gc_powerball)
b2 = Ball(20, gc_powerball)
b3 = Ball(23, gc_powerball)
b4 = Ball(25, gc_powerball)
b5 = Ball(27, gc_powerball)
b6 = Ball(17, gc_powerball, isSpecial=True)
powerball_board_E.add_ball(b1)
powerball_board_E.add_ball(b2)
powerball_board_E.add_ball(b3)
powerball_board_E.add_ball(b4)
powerball_board_E.add_ball(b5)
powerball_board_E.add_ball(b6)
# field length: 10 [['Board', 'F', '5', '23', '29', '31', '39', 'Powerball:', '9', '']]
powerball_board_F = Board(board_name="F", balls=[], gameConf=gc_powerball)
b1 = Ball(5, gc_powerball)
b2 = Ball(23, gc_powerball)
b3 = Ball(29, gc_powerball)
b4 = Ball(31, gc_powerball)
b5 = Ball(39, gc_powerball)
b6 = Ball(9, gc_powerball, isSpecial=True)
powerball_board_F.add_ball(b1)
powerball_board_F.add_ball(b2)
powerball_board_F.add_ball(b3)
powerball_board_F.add_ball(b4)
powerball_board_F.add_ball(b5)
powerball_board_F.add_ball(b6)
# field length: 10 [['Board', 'G', '13', '20', '21', '31', '38', 'Powerball:', '9', '']]
powerball_board_G = Board(board_name="G", balls=[], gameConf=gc_powerball)
b1 = Ball(13, gc_powerball)
b2 = Ball(20, gc_powerball)
b3 = Ball(21, gc_powerball)
b4 = Ball(31, gc_powerball)
b5 = Ball(38, gc_powerball)
b6 = Ball(9, gc_powerball, isSpecial=True)
powerball_board_G.add_ball(b1)
powerball_board_G.add_ball(b2)
powerball_board_G.add_ball(b3)
powerball_board_G.add_ball(b4)
powerball_board_G.add_ball(b5)
powerball_board_G.add_ball(b6)
# field length: 10 [['Board', 'H', '16', '20', '22', '37', '43', 'Powerball:', '1', '']]
powerball_board_H = Board(board_name="H", balls=[], gameConf=gc_powerball)
b1 = Ball(16, gc_powerball)
b2 = Ball(20, gc_powerball)
b3 = Ball(22, gc_powerball)
b4 = Ball(37, gc_powerball)
b5 = Ball(43, gc_powerball)
b6 = Ball(1, gc_powerball, isSpecial=True)
powerball_board_H.add_ball(b1)
powerball_board_H.add_ball(b2)
powerball_board_H.add_ball(b3)
powerball_board_H.add_ball(b4)
powerball_board_H.add_ball(b5)
powerball_board_H.add_ball(b6)
# field length: 10 [['Board', 'I', '7', '8', '15', '33', '37', 'Powerball:', '14', '']]
powerball_board_I = Board(board_name="I", balls=[], gameConf=gc_powerball)
b1 = Ball(7, gc_powerball)
b2 = Ball(8, gc_powerball)
b3 = Ball(15, gc_powerball)
b4 = Ball(33, gc_powerball)
b5 = Ball(37, gc_powerball)
b6 = Ball(14, gc_powerball, isSpecial=True)
powerball_board_I.add_ball(b1)
powerball_board_I.add_ball(b2)
powerball_board_I.add_ball(b3)
powerball_board_I.add_ball(b4)
powerball_board_I.add_ball(b5)
powerball_board_I.add_ball(b6)
# field length: 10 [['Board', 'J', '2', '11', '26', '30', '37', 'Powerball:', '17', '']]
powerball_board_J = Board(board_name="J", balls=[], gameConf=gc_powerball)
b1 = Ball(2, gc_powerball)
b2 = Ball(11, gc_powerball)
b3 = Ball(26, gc_powerball)
b4 = Ball(30, gc_powerball)
b5 = Ball(37, gc_powerball)
b6 = Ball(17, gc_powerball, isSpecial=True)
powerball_board_J.add_ball(b1)
powerball_board_J.add_ball(b2)
powerball_board_J.add_ball(b3)
powerball_board_J.add_ball(b4)
powerball_board_J.add_ball(b5)
powerball_board_J.add_ball(b6)
# field length: 9 [['Board', 'A', '4', '16', '23', '37', '42', '49', '']]
lotto_board_A = Board(board_name="A", balls=[], gameConf=gc_lotto)
b1 = Ball(4, gc_lotto)
b2 = Ball(16, gc_lotto)
b3 = Ball(23, gc_lotto)
b4 = Ball(37, gc_lotto)
b5 = Ball(42, gc_lotto)
b6 = Ball(49, gc_lotto)
lotto_board_A.add_ball(b1)
lotto_board_A.add_ball(b2)
lotto_board_A.add_ball(b3)
lotto_board_A.add_ball(b4)
lotto_board_A.add_ball(b5)
lotto_board_A.add_ball(b6)
# field length: 9 [['Board', 'B', '6', '14', '27', '33', '41', '48', '']]
lotto_board_B = Board(board_name="B", balls=[], gameConf=gc_lotto)
b1 = Ball(6, gc_lotto)
b2 = Ball(14, gc_lotto)
b3 = Ball(27, gc_lotto)
b4 = Ball(33, gc_lotto)
b5 = Ball(41, gc_lotto)
b6 = Ball(48, gc_lotto)
lotto_board_B.add_ball(b1)
lotto_board_B.add_ball(b2)
lotto_board_B.add_ball(b3)
lotto_board_B.add_ball(b4)
lotto_board_B.add_ball(b5)
lotto_board_B.add_ball(b6)
# field length: 9 [['Board', 'C', '2', '13', '18', '24', '35', '46', '']]
lotto_board_C = Board(board_name="C", balls=[], gameConf=gc_lotto)
b1 = Ball(2, gc_lotto)
b2 = Ball(13, gc_lotto)
b3 = Ball(18, gc_lotto)
b4 = Ball(24, gc_lotto)
b5 = Ball(35, gc_lotto)
b6 = Ball(46, gc_lotto)
lotto_board_C.add_ball(b1)
lotto_board_C.add_ball(b2)
lotto_board_C.add_ball(b3)
lotto_board_C.add_ball(b4)
lotto_board_C.add_ball(b5)
lotto_board_C.add_ball(b6)
# field length: 9 [['Board', 'D', '15', '20', '26', '34', '41', '47', '']]
lotto_board_D = Board(board_name="D", balls=[], gameConf=gc_lotto)
b1 = Ball(15, gc_lotto)
b2 = Ball(20, gc_lotto)
b3 = Ball(26, gc_lotto)
b4 = Ball(34, gc_lotto)
b5 = Ball(41, gc_lotto)
b6 = Ball(47, gc_lotto)
lotto_board_D.add_ball(b1)
lotto_board_D.add_ball(b2)
lotto_board_D.add_ball(b3)
lotto_board_D.add_ball(b4)
lotto_board_D.add_ball(b5)
lotto_board_D.add_ball(b6)
# field length: 9 [['Board', 'E', '12', '17', '21', '28', '36', '45', '']]
lotto_board_E = Board(board_name="E", balls=[], gameConf=gc_lotto)
b1 = Ball(12, gc_lotto)
b2 = Ball(17, gc_lotto)
b3 = Ball(21, gc_lotto)
b4 = Ball(28, gc_lotto)
b5 = Ball(36, gc_lotto)
b6 = Ball(45, gc_lotto)
lotto_board_E.add_ball(b1)
lotto_board_E.add_ball(b2)
lotto_board_E.add_ball(b3)
lotto_board_E.add_ball(b4)
lotto_board_E.add_ball(b5)
lotto_board_E.add_ball(b6)
# field length: 9 [['Board', 'F', '22', '30', '32', '38', '43', '44', '']]
lotto_board_F = Board(board_name="F", balls=[], gameConf=gc_lotto)
b1 = Ball(22, gc_lotto)
b2 = Ball(30, gc_lotto)
b3 = Ball(32, gc_lotto)
b4 = Ball(38, gc_lotto)
b5 = Ball(43, gc_lotto)
b6 = Ball(44, gc_lotto)
lotto_board_F.add_ball(b1)
lotto_board_F.add_ball(b2)
lotto_board_F.add_ball(b3)
lotto_board_F.add_ball(b4)
lotto_board_F.add_ball(b5)
lotto_board_F.add_ball(b6)
# field length: 9 [['Board', 'G', '3', '7', '14', '37', '43', '49', '']]
lotto_board_G = Board(board_name="G", balls=[], gameConf=gc_lotto)
b1 = Ball(3, gc_lotto)
b2 = Ball(7, gc_lotto)
b3 = Ball(14, gc_lotto)
b4 = Ball(37, gc_lotto)
b5 = Ball(43, gc_lotto)
b6 = Ball(49, gc_lotto)
lotto_board_G.add_ball(b1)
lotto_board_G.add_ball(b2)
lotto_board_G.add_ball(b3)
lotto_board_G.add_ball(b4)
lotto_board_G.add_ball(b5)
lotto_board_G.add_ball(b6)
# field length: 8 [['Board', 'H', '2', '14', '25', '33', '41', '49']]
lotto_board_H = Board(board_name="H", balls=[], gameConf=gc_lotto)
b1 = Ball(2, gc_lotto)
b2 = Ball(14, gc_lotto)
b3 = Ball(25, gc_lotto)
b4 = Ball(33, gc_lotto)
b5 = Ball(41, gc_lotto)
b6 = Ball(49, gc_lotto)
lotto_board_H.add_ball(b1)
lotto_board_H.add_ball(b2)
lotto_board_H.add_ball(b3)
lotto_board_H.add_ball(b4)
lotto_board_H.add_ball(b5)
lotto_board_H.add_ball(b6)
all_boards = []
all_boards.append(powerball_board_A)
all_boards.append(powerball_board_B)
all_boards.append(powerball_board_C)
all_boards.append(powerball_board_D)
all_boards.append(powerball_board_E)
all_boards.append(powerball_board_F)
all_boards.append(powerball_board_G)
all_boards.append(powerball_board_H)
all_boards.append(powerball_board_I)
all_boards.append(powerball_board_J)
all_boards.append(lotto_board_A)
all_boards.append(lotto_board_B)
all_boards.append(lotto_board_C)
all_boards.append(lotto_board_D)
all_boards.append(lotto_board_E)
all_boards.append(lotto_board_F)
all_boards.append(lotto_board_G)
all_boards.append(lotto_board_H)
p.save("all_boards.pickle", all_boards)
